<?php

$title = 'Delete user';
$this->headTitle($title);

?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete user 
    '<?php echo $this->escapeHtml($user->username); ?>'?
</p>

<?php
$url = $this->url('user', array(
    'action' => 'delete',
    'id' => $this->id,
) );
?>

<form action="<?php echo $url; ?>" method="post">
    <input type="hidden" name="id" value="<?php echo (int) $user->id; ?>" />
    <input type="submit" name="del" value="Yes" />
    <input type="submit" name="del" value="No" />
</form>
